### ISSUE TITLE
Add 'games' endpoint description

### ISSUE THREAD

**Issue by krzysztof9nowak** [progzesp22/docs#2]

**Comment by Xgreg2001** [comment]
z tego co widze to proto 1.0.4 nie ma wciaż rozpisanego interfejsu dla tworzenia/edytowania/usuwania gier ale wykorzystuje gameId jako jedno z pól przy taskach. Czy nie powinniśmy więc stowrzyć jednolitego api dla gier? @V1P0 @krzysztof9nowak @MizozPL

**Comment by MizozPL** [comment]
> 
barebones-notes.md punkt 1.
