### ISSUE TITLE
Fix spelling mistakes in proto.md

### ISSUE THREAD

**Issue by Xgreg2001** [progzesp22/docs#6]
Naucz się pisać @MizozPL. https://github.com/progzesp22/docs/blob/1b45c09389f27028aac46008b7d74c69d62dcec5/proto.md?plain=1#L7
Poza tym niezłe pole "hasło" w POST login request gdy wszytsko inne jest po angielsku.
https://github.com/progzesp22/docs/blob/1b45c09389f27028aac46008b7d74c69d62dcec5/proto.md?plain=1#L15

**Comment by MizozSU** [comment]
A ty naucz się tagować @Xgreg2001 ...

Zamknięte z: e9f20fcb7beb39fd84ffda63d559e00ef56febb1
